### ISSUE TITLE
List on Graylog Marketplace

### ISSUE THREAD

**Issue by lennartkoopmann** [dustinchilson/NLog.Targets.GraylogHttp#1]
We have launched the Graylog Marketplace: https://marketplace.graylog.org/

The Marketplace is the central directory of all Graylog add-ons and integrations, including GELF libraries.

You would help us a lot if you could submit your GELF library there as we will be shutting down the old listing of GELF libraries soon.

**Comment by dustinchilson** [comment]
Done.

[NLog.Targets.GraylogHttp](https://marketplace.graylog.org/addons/d357b17b-5811-46b3-a22e-13042c84543a)

**Comment by lennartkoopmann** [comment]
Thank you! :+1: :shipit:
