### ISSUE TITLE
Get this working with .NET Core

### ISSUE THREAD

**Issue by dls314** [dustinchilson/NLog.Targets.GraylogHttp#3]
Hi,

I haven't looked at the portability analyzer yet, but it would be nice if this worked on .NET Core instead of full framework. I'm looking at combining it with NLog.Extensions.Logging to use NLog + Graylog2 as a logging back-end for ASP.NET Core projects.

**Comment by dustinchilson** [comment]
I just got it building under netstandard1.5. NLog does not not support dnxcore50 yet so might be a while to get this working under true core.

Depends on where you want to run the app

**Comment by freerider7777** [comment]
Please add support for NLog :)
https://www.nuget.org/packages/NLog.Extensions.Logging/1.0.0-rtm-beta5

**Comment by dustinchilson** [comment]
@freerider7777 & @dls314 

I have a working version for .Net core in the NetStandard branch. The NLog5 version is still Pre-Release and I don't quite have it working for the full .NetFramework so It will not be merged/released as a package for a bit.

Let me know if it meets your needs.

**Comment by dustinchilson** [comment]
Added a MyGet Feed. Here's a build that should work for .netCore

https://www.myget.org/feed/dustinchilson/package/nuget/NLog.Targets.GraylogHttp

**Comment by dustinchilson** [comment]
This feature has been merged in as part of #8 and is available in the nuget package starting here https://www.nuget.org/packages/NLog.Targets.GraylogHttp/0.1.30
