### ISSUE TITLE
StyleCop.Analyzers should be PrivateAssets=all

### ISSUE THREAD

**Issue by snakefoot** [dustinchilson/NLog.Targets.GraylogHttp#40]
https://github.com/dustinchilson/NLog.Targets.GraylogHttp/blob/7640e607ac87c1aa2a0e1db16753765742c4d092/Directory.Build.props#L21

Should be:

```xml
<PackageReference Include="StyleCop.Analyzers" Version="1.0.2" PrivateAssets="all" />
```

**Comment by dustinchilson** [comment]
Thanks, missed that one.
