### ISSUE TITLE
Races in HTTP

### ISSUE THREAD

**Issue by Kirya522** [dustinchilson/NLog.Targets.GraylogHttp#81]
Because of races in http, logs are going into incorrect order in async and sync targets. for ex my web.config is
 <targets>

      <target name="graylogt" xsi:type="GraylogHttp" facility="WebApi" graylogServer="http://graylog" graylogPort="12201">
        <parameter name="current_user" layout="${aspnet-user-identity}" />
        <parameter name="exception_type" layout="${exception:Type}" />
        <parameter name="request" layout="${aspnet-request-method} ${aspnet-request-url}" />
        <parameter name="site" layout="${iis-site-name} ${aspnet-appbasepath}" />
        <parameter name="request_body" layout="${onexception:${aspnet-request-posted-body}:when=level>=LogLevel.Error}" />
      </target>
    </targets>
    <rules>
      <logger name="*" minlevel="debug" writeTo="graylogt" />
    </rules>

when async methods logging steps 
But logs **HAVE THE SAME TIME** and **INCORRECT ORDER** and this is the example, where procedure in db starts and ends, but end log come before
![image](https://user-images.githubusercontent.com/33904040/62442069-13ec8a80-b770-11e9-94f2-bc7f44442868.png)

**Comment by dustinchilson** [comment]
are you running the targets in async mode? https://github.com/nlog/NLog/wiki/AsyncWrapper-target#async-attribute

**Comment by Kirya522** [comment]
yes, because it takes 0.2sec to send logs and in "sync" mode it blocks the thread

**Comment by Kirya522** [comment]
well the problem can't be resolved without queue, so as a result logs come out of order

**Comment by Kirya522** [comment]
I think it should be a some sequence or something like that to make logs unique

**Comment by Kirya522** [comment]
So this is graylog bugs, I commented a solution for it. https://github.com/NLog/NLog/issues/3542
